@BASE_URL=http://localhost:3001
@access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmNGQyZTAxLWE2ODgtNDhiZC1iNzgwLTkxYjBmZTEzZDhlYyIsImVtYWlsIjoiam9obi5kb2UxQGV4YW1wbGUuY29tIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNzQ5MDIyMzY5LCJleHAiOjE3NDkwNTgzNjl9.KY_hc8jJIfUg1cKGjqv69d-jwQn70rbO4-EN1nvIbxY


### Signup User

POST {{BASE_URL}}/user/signup
Content-Type: application/json

{
    "name": "John Doe 1",
    "email": "john.doe1@example.com",
    "password": "password"
}


### Login User
POST {{BASE_URL}}/auth/login
Content-Type: application/json

{
    "email": "john.doe1@example.com",
    "password": "password"
}



### Get User
GET {{BASE_URL}}/user/me
Authorization: Bearer {{access_token}}




