
@BASE_URL=http://localhost:3000
@TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImVmNGQyZTAxLWE2ODgtNDhiZC1iNzgwLTkxYjBmZTEzZDhlYyIsImVtYWlsIjoiam9obi5kb2UxQGV4YW1wbGUuY29tIiwiZXhwaXJlc0luIjozNjAwMCwiaWF0IjoxNzUwMjMwMDkyLCJleHAiOjE3NTAyNjYwOTJ9.SUmXAiv3ktC-v9yubOWrptf7VrnPOHr8XjdZT3Cel-E


### Create Reservation
POST {{BASE_URL}}/reservation
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
    "placeId": "1",
    "startDate": "2025-06-18",
    "endDate": "2025-06-20",
    "status": "pending"
}
